name: Build MusicVoice

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle 8.2.1
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1
          arguments: assembleDebug
