name: Build MusicVoice

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools

      - name: Gradle build (assembleDebug)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1
          build-root-directory: app
          arguments: assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MusicVoice-debug-apk
          path: app/build/outputs/apk/debug/*.apk
